### ISSUE TITLE
Migrate azure pipeline to github action

### ISSUE THREAD

**Issue by Razzeee** [xbmc/visualization.matrix#1]

**Comment by Razzeee** [comment]
Also role travis and appveyor builds into this and get rid of them

**Comment by sarbes** [comment]
Do you have an example how to do so? I have no clue.

**Comment by Razzeee** [comment]
As far as I remember the syntax of azure pipelines is pretty much the one you need for github actions. I can have a go at it if you want.

**Comment by sarbes** [comment]
Sure, be my guest. I have yet to see a binary add-on using this to get an idea.

**Comment by AlwinEsch** [comment]
Have added to Azure pipeline yesterday, for @sarbes was no account with ...@teamkodi.onmicrosoft.com present to add as user.

**Comment by AlwinEsch** [comment]
@sarbes this issue can be closed.
